// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexDesk.Infrastructure;

#nullable disable

namespace NexDesk.Infrastructure.Migrations
{
    [DbContext(typeof(NexDeskDbContext))]
    [Migration("20260414112000_RemoveIsInternalFromComments")]
    partial class RemoveIsInternalFromComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Note: This is a partial Designer file showing the migration target state
            // The full model is defined in NexDeskDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
